[tool.pytest.ini_options]
pythonpath = [
  "src"
]
filterwarnings = [
    # Ignore all DeprecationWarnings from the opencensus library and its submodules,
    # as we cannot fix third-party code.
    "ignore::DeprecationWarning:opencensus.*"
]

[tool.coverage.report]
exclude_lines = [
    "if __name__ == .__main__.:",
    "pragma: no cover",            # Allows for explicit `# pragma: no cover` comments
]